### ISSUE TITLE
The predict methods use a normal distribution for all models, but to use a normal approximation on Bradley-Terry the variance needs to be multiplied by a constant 

### ISSUE THREAD

**Issue by Jayensee** [vivekjoshy/openskill.py#146]
According to Weng & Lin 2011 "A Bayesian Approximation Method for Online Ranking" to replace the logistic distribution used in Bradley-Terry with a normal approximation the standard deviation should be the c parameter multiplied by pi divided by the square root of 3
![image](https://github.com/user-attachments/assets/136d3eff-2feb-43d8-909e-1a61dbf0124b)

Wikipedia agrees with this as well
![image](https://github.com/user-attachments/assets/831f725e-3ca6-4c2f-a250-8b2eeff3b8a5)

It seems the predict methods are the same across the different models, so they're missing that constant
https://github.com/vivekjoshy/openskill.py/blob/a7d6206f15f3aac930f4bba9aa747b4d3cf75766/openskill/models/weng_lin/bradley_terry_full.py#L849

Also, I don't know if a normal approximation makes sense for Plackett-Luce

**Comment by vivekjoshy** [comment]
After investigating this, the reason these predict methods were designed this way is to scale outputs values between certain ranges. After implementing these changes locally it has virtually no effect on the accuracy as seen in the benchmarks. As such this will not be implemented. Feel free to reopen, or comment here with any practical implementation ideas that are justified by empirical observations.
